name: "sonarqube"
repository: github.com/ctsyeh/trivy-plugin-sonarqube
version: "0.2.3"
usage: Convert Trivy JSON report to SonarQube format
description: |-
  A Trivy plugin that converts JSON report to SonarQube compatible format (https://docs.sonarqube.org/latest/analysis/generic-issue/).
  Usage: trivy sonarqube TRIVY-REPORT > SONARQUBE-REPORT
platforms:
  - uri: https://github.com/ctsyeh/trivy-plugin-sonarqube/releases/download/v0.2.3/trivy-sonarqube.tar.gz
    bin: sonarqube.py
